apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: conversion
  namespace: prod
spec:
  awsName: currency-conversion-service-vn
  podSelector:
    matchLabels:
      app: conversion
  listeners:
    - portMapping:
        port: 8100
        protocol: http
  serviceDiscovery:
    dns:
      hostname: conversion.prod.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: conversion
  namespace: prod
spec:
  awsName: conversion
  provider:
    virtualNode:
      virtualNodeRef:
        name: conversion